// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database as GeneratedDatabase } from './types';

type OptionalTenantId<T> = T extends { tenant_id: infer V }
  ? Omit<T, 'tenant_id'> & { tenant_id?: V }
  : T;

type PatchTable<T> = T extends { Row: any; Insert: infer I; Update: any; Relationships: any }
  ? Omit<T, 'Insert'> & { Insert: OptionalTenantId<I> }
  : T;

type PatchTables<T> = {
  [K in keyof T]: PatchTable<T[K]>;
};

type Database = Omit<GeneratedDatabase, 'public'> & {
  public: Omit<GeneratedDatabase['public'], 'Tables'> & {
    Tables: PatchTables<GeneratedDatabase['public']['Tables']>;
  };
};

const SUPABASE_URL = "https://bpkddmxpyeyxvjyebull.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJwa2RkbXhweWV5eHZqeWVidWxsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA3NTQ5NzEsImV4cCI6MjA5NjMzMDk3MX0.vHVvxVI2x87aWeiNlzwIoCqU1y-tNlvbc0j_PJcRuvk";

let currentTenantId: string | null = null;
const tenantChangeListeners = new Set<(prev: string | null, next: string | null) => void>();

export function getTenantId(): string | null {
  return currentTenantId;
}

export function setTenantHeader(tenantId: string | null): void {
  const prev = currentTenantId;
  if (prev === tenantId) return;
  currentTenantId = tenantId;
  tenantChangeListeners.forEach((cb) => cb(prev, tenantId));
}

export function registerTenantChangeListener(
  callback: (prev: string | null, next: string | null) => void
): () => void {
  tenantChangeListeners.add(callback);
  return () => tenantChangeListeners.delete(callback);
}

const originalFetch = globalThis.fetch;

function tenantAwareFetch(input: RequestInfo | URL, init?: RequestInit): Promise<Response> {
  const headers = new Headers(init?.headers);
  const tenantId = getTenantId();
  if (tenantId) {
    headers.set('x-tenant-id', tenantId);
  } else {
    headers.delete('x-tenant-id');
  }
  return originalFetch(input, { ...init, headers });
}

export const supabase = createClient<Database, 'public', 'public'>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    fetch: tenantAwareFetch,
  },
});
